name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      # 安全检查：Govulncheck 依赖漏洞扫描
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test=false $(go list ./... | grep -v vendor | grep -v 'opt/hostedtoolcache/go')

      # 代码质量检查：Golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run --skip-dirs vendor --skip-dirs third_party ./... | grep -v 'opt/hostedtoolcache/go'

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...