name: Auto Tag Commit

on:
  push:
    branches:
      - main

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag
        id: latest_tag
        run: echo ::set-output name=TAG::$(git describe --abbrev=0 --tags)

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r -a version_parts <<< "${{ steps.latest_tag.outputs.TAG }}"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          patch="$(( ${version_parts[2]} + 1 ))"
          echo "v$major.$minor.$patch" >> version.txt

      - name: Tag commit
        if: steps.latest_tag.outputs.TAG != ''
        run: |
          new_tag=$(cat version.txt)
          git tag -am 'update tag' $new_tag
          git push --tags
          echo "Tagged commit with version $new_tag"
